{% set name = "partsegdata" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/PartSegData-{{ version }}.tar.gz
  sha256: 1a48d0f8eb394420879a6308f2917f13ca9e525c4dc16d1f7d870b6fd5393d64

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools 
    - setuptools-scm >=8
  run:
    - python >={{ python_min }}

test:
  imports:
    - PartSegData
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://4dnucleome.cent.uw.edu.pl/PartSeg/
  summary: PartSeg data files
  license: BSD-3-Clause
  license_file: License.txt

extra:
  recipe-maintainers:
    - conda-forge/napari
    - Czaki
